# Generated by Django 4.2.3 on 2023-07-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_name', models.CharField(max_length=300)),
                ('ovozlar_soni', models.IntegerField(default=0)),
            ],
        ),
    ]
