# Generated by Django 4.2.3 on 2023-07-11 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_menus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='ovozlar_soni',
        ),
        migrations.AddField(
            model_name='menus',
            name='ovozlar_soni',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
